# Site settings
title: Kostask
email: kostas@pointblank.gr
description: >
    Drupal pianist @ Point Blank
baseurl: ""
url: ""
twitter_username: kostask_
github_username:  KostasBlank

# Build settings
markdown: kramdown

include: ['_pages']
